version: '3.8'

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: patolino
      POSTGRES_PASSWORD: pato
      POSTGRES_DB: pato-palavra-db
    ports:
      - "5432:5432"
    volumes:
      - pato-palavra-data:/var/lib/postgresql/data

volumes:
  pato-palavra-data:
    driver: local
