name: Java CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 24
      uses: actions/setup-java@v3
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: target
        
    - name: Deploy to Server using appleboy/ssh-action
      uses: appleboy/ssh-action@master # Or pin to a specific version like @v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        
        source: "target/*.jar" 

        target: "${{ secrets.TARGET_DIR }}/${{ secrets.APP_JAR_NAME }}"
        script: |
          echo "JAR file copied to ${{ secrets.TARGET_DIR }}/${{ secrets.APP_JAR_NAME }}"
          
          cd ${{ secrets.TARGET_DIR }}
          
          sudo pkill -f 'java -jar ${{ secrets.APP_JAR_NAME }}' || echo "No process to kill or failed to kill."
          
          sleep 5 

          echo "Starting new application: ${{ secrets.APP_JAR_NAME }}"

          nohup java -jar -Dserver.port=8080 ${{ secrets.APP_JAR_NAME }} --spring.profiles.active=prod > app.log 2>&1 &
          
          echo "Application deployed and started. Check logs with: tail -f ${{ secrets.TARGET_DIR }}/app.log"
          echo "To check if process is running: ps aux | grep '${{ secrets.APP_JAR_NAME }}'"
